remove pagy extras
after upgrading to Ruby 3.3.4 and Rails 7.2 I've got

        LoadError: cannot load such file -- pagy/extras/items (LoadError)

When I checked [pagy-extras gem](https://github.com/ddnexus/pagy-extras) I saw it is deprected and integrated into pagy gem, so we can remove these requires now